const recipes = [
  {
    id: "truffle-pea-pasta",
    title: "Creamy Truffle Pea Pasta",
    emoji: "🍝",
    description: "Silky pea pasta with zucchini, parmesan and truffle.",
    category: "main",
    tags: ["vegetarian", "high protein", "quick", "pasta", "post-workout"],
    servings: 1,
    time: 30,
    calories: 520,
    protein: 35,
    carbs: 63,
    fat: 14,
    fiber: 10,
    equipment: ["thermomix", "air fryer optional"],
    ingredients: [
      "70 g dry pea pasta",
      "150 g zucchini, diced",
      "80 g skyr or thick yogurt",
      "15 g parmesan, finely grated",
      "5 g olive oil",
      "1 tsp truffle paste or 1/2 tsp truffle oil",
      "1/2 tsp garlic powder",
      "Salt and black pepper",
      "60–100 ml pasta water"
    ],
    steps: [
      "Bring salted water to a boil and cook the pea pasta until just tender; reserve at least 100 ml pasta water before draining.",
      "Toss zucchini with the olive oil, salt and pepper and air-fry at 195°C for 8–10 minutes, shaking once.",
      "In a bowl mix skyr, parmesan, truffle, garlic powder and 40 ml hot pasta water until smooth.",
      "Take the pan off the heat. Add pasta, zucchini and sauce, tossing quickly so the yogurt does not split.",
      "Add more pasta water a tablespoon at a time until glossy. Taste and finish with black pepper."
    ],
    note: "Adjust pasta according to hunger! Perfect for post-workout meals, since it is lower in fat. Add more parmesan to increase the fat content."
  },
  {
    id: "sweet-sour-tofu",
    title: "Sweet & Sour Tofu",
    emoji: "🥢",
    description: "Crispy tofu, sweet potato and vegetables in a glossy sweet-sour sauce.",
    category: "main",
    tags: ["vegetarian", "high protein", "air fryer", "quick"],
    servings: 1,
    time: 15,
    calories: 540,
    protein: 31,
    carbs: 67,
    fat: 18,
    fiber: 10,
    equipment: ["air fryer"],
    ingredients: [
      "200 g firm tofu, pressed and cubed",
      "180 g sweet potato, 2 cm cubes",
      "150 g bell pepper and courgette",
      "5 g cornstarch",
      "5 g sesame or olive oil",
      "20 g ketchup",
      "10 g soy sauce",
      "12 g rice vinegar",
      "8 g honey or maple syrup",
      "1 tsp grated ginger",
      "1 small garlic clove",
      "40 ml water"
    ],
    steps: [
      "Preheat the air fryer to 195°C. Toss sweet potato with half the oil and air-fry 10 minutes.",
      "Toss tofu with cornstarch, remaining oil and a pinch of salt. Add to the basket with the vegetables and air-fry another 10–12 minutes, shaking twice.",
      "Sauce: add ketchup, soy, vinegar, honey, ginger, garlic and water; cook 4 min/100°C/speed 2, measuring cup off.",
      "Toss the crisp tofu and vegetables with the hot sauce just before serving so the tofu stays crisp."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "taco-rice-bowl",
    title: "Halloumi Taco Rice Bowl",
    emoji: "🌮",
    description: "Rice, edamame, halloumi and crunchy taco toppings.",
    category: "main",
    tags: ["vegetarian", "high protein", "bowl", "quick"],
    servings: 1,
    time: 20,
    calories: 575,
    protein: 32,
    carbs: 65,
    fat: 22,
    fiber: 11,
    equipment: ["air fryer"],
    ingredients: [
      "55 g dry whole-grain rice",
      "100 g shelled edamame",
      "70 g halloumi, sliced",
      "80 g corn or black beans",
      "120 g shredded lettuce/cabbage and tomato",
      "40 g skyr or yogurt",
      "1/2 lime",
      "1 tsp taco seasoning",
      "10 g crushed tortilla chips"
    ],
    steps: [
      "Cook rice according to the package and stir through the edamame for the final 2 minutes to heat it.",
      "Cook halloumi at 190°C for 6–8 minutes, turning once.",
      "Mix yogurt, lime juice and taco seasoning.",
      "Layer rice, edamame, vegetables and corn/beans in a bowl. Add halloumi, yogurt-lime sauce and crushed tortilla chips."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "lemon-chicken-quinoa",
    title: "Lemon Chicken, Edamame & Quinoa Bowl",
    emoji: "🍋",
    description: "Lemony chicken with quinoa, edamame and a fresh yogurt sauce.",
    category: "main",
    tags: ["high protein", "bowl", "meal prep", "post-workout"],
    servings: 1,
    time: 25,
    calories: 560,
    protein: 48,
    carbs: 59,
    fat: 14,
    fiber: 10,
    equipment: ["thermomix", "air fryer"],
    ingredients: [
      "140 g chicken breast or equivalent plant-based protein",
      "55 g dry quinoa",
      "80 g edamame",
      "150 g cucumber/courgette",
      "80 g Greek yogurt or skyr",
      "1/2 lemon, zest and juice",
      "1 small garlic clove",
      "5 g olive oil",
      "Dill or parsley",
      "Salt and pepper"
    ],
    steps: [
      "Rinse quinoa and cook in about 120 ml water for 12–15 minutes; rest covered 5 minutes.",
      "Season chicken with salt, pepper and lemon zest. Air-fry at 190°C for 10–12 minutes, or pan-cook in oil over medium heat until cooked through.",
      "Add edamame to boiling water for 3–4 minutes and drain.",
      "Mix yogurt with lemon juice, garlic and herbs.",
      "Slice chicken and assemble with quinoa, edamame and vegetables. Spoon over the sauce."
    ],
    note: "Chicken is 43g of protein per serving; plant-based protein may be lower. Approximate macros per serving."
  },
  {
    id: "mango-chicken-bowl",
    title: "Mango Chicken Rice Bowl",
    emoji: "🥭",
    description: "Sweet mango, savoury chicken, rice and crunchy vegetables.",
    category: "main",
    tags: ["high protein", "bowl", "fresh", "post-workout"],
    servings: 1,
    time: 20,
    calories: 555,
    protein: 43,
    carbs: 72,
    fat: 10,
    fiber: 8,
    equipment: ["hob", "air fryer optional"],
    ingredients: [
      "140 g chicken breast",
      "60 g dry rice",
      "100 g mango, diced",
      "120 g cucumber",
      "60 g edamame",
      "60 g yogurt",
      "1/2 lime",
      "10 g soy sauce",
      "1 tsp honey",
      "Garlic powder and pepper"
    ],
    steps: [
      "Cook the rice and edamame.",
      "Season chicken with garlic powder and pepper. Air-fry at 190°C for 10–12 minutes or pan-sear until cooked.",
      "Mix yogurt with lime juice. Separately mix soy sauce with honey and a squeeze of lime.",
      "Arrange rice, cucumber, mango and edamame. Slice the chicken over the bowl and finish with both sauces."
    ],
    note: "Lower fat - perfect for post-workout meals. Approximate macros per serving."
  },
  {
    id: "chickpea-pesto-aubergine",
    title: "Pesto Chickpea & Aubergine Bowl",
    emoji: "🍆",
    description: "Roasted aubergine and chickpeas with pesto, feta and lemon yogurt.",
    category: "main",
    tags: ["vegetarian", "bowl", "air fryer", "high fibre"],
    servings: 1,
    time: 25,
    calories: 520,
    protein: 24,
    carbs: 48,
    fat: 27,
    fiber: 20,
    equipment: ["air fryer"],
    ingredients: [
      "250 g aubergine, cubed",
      "160 g chickpeas, drained",
      "15 g pesto",
      "35 g feta",
      "80 g skyr or yogurt",
      "100 g courgette or leafy greens",
      "5 g olive oil",
      "1/2 lemon",
      "Paprika, garlic powder, salt and pepper"
    ],
    steps: [
      "Preheat air fryer to 195°C. Toss aubergine with oil, paprika, garlic, salt and pepper; air-fry 10 minutes.",
      "Add chickpeas and courgette, shake well and air-fry another 8–10 minutes until browned.",
      "Mix yogurt with lemon juice and a pinch of salt.",
      "Toss the hot vegetables and chickpeas with pesto. Plate and top with feta and lemon yogurt."
    ],
    note: "Approximate macros per serving. Add tuna for more protein (approx. 20 g per 100 g)."
  },
  {
    id: "crispy-aubergine-tofu",
    title: "Crispy Aubergine & Tofu Tray",
    emoji: "🔥",
    description: "Crispy air-fried tofu and aubergine with a creamy sweet-savoury drizzle.",
    category: "main",
    tags: ["vegetarian", "high protein", "spicy"],
    servings: 1,
    time: 25,
    calories: 500,
    protein: 32,
    carbs: 45,
    fat: 22,
    fiber: 12,
    equipment: ["air fryer"],
    ingredients: [
      "180 g firm tofu",
      "250 g aubergine",
      "100 g chickpeas, drained",
      "5 g olive oil",
      "10 g soy sauce",
      "1 tsp smoked paprika",
      "1/2 tsp cumin",
      "1/2 tsp garlic powder",
      "80 g yogurt/skyr",
      "8 g honey",
      "1 tsp sriracha optional"
    ],
    steps: [
      "Preheat air fryer to 200°C. Cube tofu and aubergine.",
      "Toss tofu with soy sauce and half the spices; toss aubergine and chickpeas with oil and remaining spices.",
      "Air-fry everything for 14–16 minutes, shaking every 5 minutes, until tofu is crisp and aubergine browned.",
      "Mix yogurt with honey and optional sriracha. Spoon over the hot tray."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "sticky-chicken-potatoes",
    title: "Sticky Sesame Chicken & Potatoes",
    emoji: "🍗",
    description: "Crispy potatoes and chicken with a sticky soy-honey glaze.",
    category: "main",
    tags: ["high protein", "air fryer", "comfort"],
    servings: 1,
    time: 35,
    calories: 625,
    protein: 45,
    carbs: 76,
    fat: 15,
    fiber: 9,
    equipment: ["air fryer", "Thermomix optional"],
    ingredients: [
      "250 g potatoes, cubed",
      "150 g chicken breast, cubed",
      "200 g broccoli or mixed vegetables",
      "8 g olive oil",
      "18 g soy sauce",
      "12 g honey",
      "1 tsp grated ginger",
      "1 garlic clove",
      "5 g sesame seeds",
      "Optional sriracha"
    ],
    steps: [
      "Preheat air fryer to 195°C. Toss potatoes with 5 g oil and salt; air-fry 14 minutes.",
      "Add chicken tossed with remaining oil and vegetables. Air-fry 10–12 minutes more, shaking twice, until chicken is cooked and potatoes crisp.",
      "Thermomix glaze: add soy, honey, ginger, garlic and 20 ml water; cook 4 min/100°C/speed 2. Pan option: simmer 3–4 minutes.",
      "Toss chicken in glaze and serve with potatoes and vegetables. Sprinkle sesame seeds on top."
    ],
    note: "Makes a small serving - pair with extra vegetables for a larger meal. Approximate macros per serving."
  },
  {
    id: "chicken-chickpea-tahini",
    title: "Chicken & Crispy Chickpea Tahini Bowl",
    emoji: "🥙",
    description: "Chicken, chickpeas and roasted vegetables with creamy tahini sauce.",
    category: "main",
    tags: ["high protein", "bowl", "air fryer"],
    servings: 1,
    time: 30,
    calories: 560,
    protein: 40,
    carbs: 55,
    fat: 20,
    fiber: 13,
    equipment: ["air fryer"],
    ingredients: [
      "120 g chicken breast",
      "120 g chickpeas, drained",
      "250 g zucchini/aubergine/onion",
      "40 g dry rice",
      "8 g olive oil",
      "12 g tahini",
      "60 g yogurt",
      "5 g honey",
      "8 g soy sauce",
      "1/2 lemon"
    ],
    steps: [
      "Cook the rice.",
      "Preheat air fryer to 195°C. Toss vegetables and chickpeas with half the oil and season; air-fry 8 minutes.",
      "Add chicken coated with remaining oil and seasoning. Air-fry another 10–12 minutes until cooked.",
      "Whisk tahini, yogurt, honey, soy sauce and lemon with 1–2 tbsp water.",
      "Build the bowl with rice, crispy vegetables/chickpeas and chicken; drizzle with sauce."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "lentil-pasta-peanut",
    title: "Peanut Lentil Pasta Bowl",
    emoji: "🥜",
    description: "Lentil pasta with a creamy peanut-soy sauce and crunchy vegetables.",
    category: "main",
    tags: ["vegetarian", "high protein", "pasta"],
    servings: 1,
    time: 15,
    calories: 525,
    protein: 31,
    carbs: 68,
    fat: 16,
    fiber: 14,
    equipment: ["hob"],
    ingredients: [
      "75 g dry lentil pasta",
      "18 g peanut butter",
      "12 g soy sauce",
      "1/2 lime or 10 g rice vinegar",
      "1 tsp grated ginger",
      "100 g cucumber",
      "80 g carrot",
      "50 g edamame",
      "60–100 ml pasta water"
    ],
    steps: [
      "Cook lentil pasta until just tender; reserve 100 ml pasta water.",
      "Whisk peanut butter, soy sauce, lime/vinegar, ginger and 40 ml pasta water into a smooth sauce.",
      "Drain pasta and toss with the sauce and edamame.",
      "Fold through cucumber and carrot for crunch; loosen with more pasta water if needed."
    ],
    note: "Replace for 40-50g of sugar free satésauce for lower calories."
  },
  {
    id: "gyros-mushroom-pasta",
    title: "Creamy Gyros, Mushroom & Zucchini Pasta",
    emoji: "🍄",
    description: "Creamy savoury pasta with gyros-style pieces, mushroom and zucchini.",
    category: "main",
    tags: ["high protein", "pasta", "comfort"],
    servings: 1,
    time: 20,
    calories: 590,
    protein: 39,
    carbs: 69,
    fat: 17,
    fiber: 8,
    equipment: ["hob"],
    ingredients: [
      "70 g dry pasta",
      "120 g Vivera gyros/shawarma or lean gyros meat",
      "150 g mushrooms",
      "120 g zucchini",
      "80 g skyr or light cream cheese",
      "15 g parmesan",
      "5 g olive oil",
      "1 tsp gyros seasoning",
      "80 ml pasta water"
    ],
    steps: [
      "Cook pasta in salted water; reserve pasta water.",
      "Heat oil in a large pan and brown the gyros pieces for 3–4 minutes.",
      "Add mushrooms and zucchini and cook until browned and reduced.",
      "Lower heat. Stir in skyr/light cream cheese, parmesan and 50 ml pasta water.",
      "Add pasta and toss until creamy. Add more pasta water if needed and season."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "zucchini-boats",
    title: "Zucchini Boats",
    emoji: "🥒",
    description: "Zucchini stuffed with plant mince and creamy cheese.",
    category: "main",
    tags: ["vegetarian", "high protein", "air fryer", "quick"],
    servings: 1,
    time: 20,
    calories: 375,
    protein: 35,
    carbs: 24,
    fat: 15,
    fiber: 8,
    equipment: ["air fryer"],
    ingredients: [
      "1 large zucchini, about 300 g",
     "150 g plant mince",
     "100 g cottage cheese",
     "15 g parmesan",
     "1 tsp Dijon mustard",
     "1 tsp garlic powder",
     "1/2 tsp Italian herbs",
     "Salt and pepper"
   ],
   steps: [
     "Halve zucchini lengthwise and scoop out a shallow channel; chop the scooped flesh.",
     "Mix zucchini flesh with plant mince, cottage cheese, Dijon, garlic powder and Italian herbs.",
    "Fill the zucchini halves and sprinkle parmesan on top.",
    "Air-fry at 190°C for 12–15 minutes until zucchini is tender and the top is golden."
   ],
    note: "Approximate macros per serving."
  },
  {
    id: "smoked-tofu-slices",
    title: "Hoisin-Miso Smoked Tofu Slices",
    emoji: "🥪",
    description: "Savoury meal-prep tofu slices for toast and sandwiches.",
    category: "breakfast",
    tags: ["vegetarian", "meal prep", "high protein"],
    servings: 4,
    time: 25,
    calories: 115,
    protein: 12,
    carbs: 7,
    fat: 5,
    fiber: 2,
    equipment: ["air fryer", "Thermomix optional"],
    ingredients: [
      "400 g smoked or firm tofu",
      "20 g hoisin",
      "15 g white miso",
      "15 g soy sauce",
      "10 g rice vinegar",
      "1/2 tsp garlic powder",
      "30 ml water"
    ],
    steps: [
      "Slice tofu into thin 5–7 mm pieces.",
      "Thermomix marinade: add hoisin, miso, soy, vinegar, garlic and water; mix 15 sec/speed 4. Bowl option: whisk smooth.",
      "Coat tofu and marinate at least 10 minutes.",
      "Air-fry at 190°C for 10–12 minutes, flipping halfway, until dark at the edges.",
      "Cool fully before storing. Divide into 4 portions."
    ],
    note: "Macros are per 1/4 batch."
  },
  {
    id: "tempeh-breakfast-slices",
    title: "Miso-Hoisin Tempeh Slices",
    emoji: "🍞",
    description: "Chewy savoury tempeh slices for breakfast and sandwiches.",
    category: "breakfast",
    tags: ["vegetarian", "meal prep", "high protein"],
    servings: 4,
    time: 30,
    calories: 230,
    protein: 20,
    carbs: 9,
    fat: 12,
    fiber: 7,
    equipment: ["air fryer"],
    ingredients: [
      "400 g tempeh",
      "15 g miso",
      "25 g hoisin",
      "15 g soy sauce",
      "10 g rice vinegar",
      "50 ml water",
      "1/2 tsp smoked paprika",
      "1/2 tsp garlic powder"
    ],
    steps: [
      "Steam tempeh for 8 minutes to soften bitterness, then cool enough to handle.",
      "Slice into thin strips.",
      "Thermomix marinade: mix remaining ingredients 15 sec/speed 4. Coat tempeh and rest 10 minutes.",
      "Air-fry at 190°C for 10–12 minutes, turning once, until browned.",
      "Cool and divide into 4 portions."
    ],
    note: "Macros are per 1/4 batch."
  },
  {
    id: "carrot-cake-oats",
    title: "Fluffy Carrot Cake Baked Oats",
    emoji: "🥕",
    description: "Soft carrot-cake oats with protein and a creamy topping.",
    category: "breakfast",
    tags: ["sweet", "high protein", "air fryer"],
    servings: 1,
    time: 20,
    calories: 430,
    protein: 30,
    carbs: 45,
    fat: 16,
    fiber: 8,
    equipment: ["air fryer", "Thermomix optional"],
    ingredients: [
      "40 g oats",
      "80 g finely grated carrot",
      "1 egg",
      "25 g vanilla protein powder",
      "60 g skyr",
      "60 ml milk",
      "4 g baking powder",
      "1 tsp cinnamon",
      "Pinch nutmeg and salt",
      "15 g walnuts or 15g nut butter for topping"
    ],
    steps: [
      "Thermomix option: add carrot and chop 4 sec/speed 5. Add oats and mill 10 sec/speed 8 if you want a cake-like texture.",
      "Mix oats, carrot, egg, protein powder, 40 g skyr, milk, baking powder and spices.",
      "Pour into a greased heatproof dish. Air-fry at 170°C for 13–16 minutes until just set in the centre.",
      "Rest 3 minutes. Top with remaining skyr and optional walnuts."
    ],
    note: "Approximate macros per serving. Add sweetener to taste if desired."
  },
  {
    id: "protein-ice-cream",
    title: "Protein Ice-Cream Bowl",
    emoji: "🍓",
    description: "Thick frozen banana-berry soft serve with protein.",
    category: "snack",
    tags: ["sweet", "high protein", "quick"],
    servings: 1,
    time: 5,
    calories: 285,
    protein: 23,
    carbs: 48,
    fat: 3,
    fiber: 8,
    equipment: ["Thermomix", "blender"],
    ingredients: [
      "120 g frozen banana",
      "150 g frozen berries",
      "30 g protein powder",
      "30-60ml cold water, as needed for blending",
      "100 g skyr optional for extra creaminess and post-gym protein boost"
    ],
    steps: [
      "Thermomix: add frozen fruit and chop 10 sec/speed 8; scrape down.",
      "Add protein powder and milk; blend 40 sec/speed 6, using the spatula through the lid if needed.",
      "Add skyr and blend 15 sec/speed 5.",
      "Serve immediately for soft-serve texture or freeze 20–30 minutes for firmer ice cream."
    ],
    note: "Approximate macros without skyr. Adding 100 g skyr adds approximately 60 kcal (for 345 kcal) and 11 g protein (for 34g protein)."
  },
  {
    id: "brownie-batter-bowl",
    title: "Brownie Batter Protein Bowl",
    emoji: "🍫",
    description: "Thick chocolate protein bowl with brownie-batter texture.",
    category: "snack",
    tags: ["sweet", "high protein", "quick"],
    servings: 1,
    time: 5,
    calories: 300,
    protein: 30,
    carbs: 29,
    fat: 8,
    fiber: 6,
    equipment: [],
    ingredients: [
      "200 g skyr or thick high-protein yogurt",
      "25 g chocolate protein powder",
      "10 g cocoa powder",
      "10 g peanut butter",
      "Sweetener to taste",
      "Pinch of salt",
      "15–30 ml milk"
    ],
    steps: [
      "Mix skyr, protein powder, cocoa and salt until very thick.",
      "Add milk 1 tsp at a time until glossy and spoonable.",
      "Sweeten to taste and swirl through peanut butter.",
      "Let stand 3–5 minutes so the protein powder hydrates and the texture thickens."
    ],
    note: "Approximate macros per bowl."
  },
  {
    id: "banana-protein-muffins",
    title: "Fluffy Banana Protein Muffins",
    emoji: "🧁",
    description: "Soft banana-oat protein muffins for meal prep.",
    category: "snack",
    tags: ["sweet", "high protein", "meal prep"],
    servings: 6,
    time: 30,
    calories: 165,
    protein: 10,
    carbs: 22,
    fat: 4,
    fiber: 3,
    equipment: ["oven", "air fryer optional", "Thermomix optional"],
    ingredients: [
      "180 g ripe banana",
      "120 g oat flour",
      "60 g vanilla protein powder",
      "2 eggs",
      "120 g yogurt",
      "80 ml milk",
      "8 g baking powder",
      "1 tsp cinnamon",
      "Pinch salt"
    ],
    steps: [
      "Thermomix: blend banana, eggs, yogurt and milk 15 sec/speed 5. Add dry ingredients and mix 12 sec/speed 4. Otherwise whisk by hand.",
      "Divide batter among 6 muffin cups.",
      "Oven: bake at 180°C for 18–22 minutes. Air fryer: 160°C for 12–15 minutes in heatproof silicone cups.",
      "Cool at least 10 minutes before removing from cups."
    ],
    note: "Approximate macros per muffin."
  },
  {
    id: "banana-cashew-bars",
    title: "Banana-Cashew Cheesecake Protein Bars",
    emoji: "🍌",
    description: "Oat-date cashew bars with tangy protein frosting.",
    category: "snack",
    tags: ["sweet", "high protein", "Thermomix", "meal prep"],
    servings: 8,
    time: 25,
    calories: 190,
    protein: 10,
    carbs: 25,
    fat: 6,
    fiber: 3,
    equipment: ["Thermomix", "fridge"],
    ingredients: [
      "100 g oats",
      "70 g vanilla protein powder",
      "120 g dates",
      "100 g banana",
      "40 g cashew butter",
      "Pinch salt",
      "120 g soy yogurt or skyr",
      "25 g protein powder for frosting",
      "1 tsp vanilla"
    ],
    steps: [
      "Add oats to Thermomix and mill 10 sec/speed 9.",
      "Add 45 g protein powder, dates, banana, cashew butter and salt; blend 20 sec/speed 6, scrape, then 10 sec/speed 6.",
      "Press firmly into a lined small container.",
      "Mix yogurt, remaining protein powder and vanilla 15 sec/speed 4; spread over base.",
      "Chill at least 2 hours, then cut into 8 bars."
    ],
    note: "Approximate macros per bar."
  },
  {
    id: "kaki-mousse",
    title: "Persimmon Protein Mousse",
    emoji: "🧡",
    description: "Naturally thick persimmon-vanilla protein mousse.",
    category: "snack",
    tags: ["sweet", "high protein", "quick"],
    servings: 1,
    time: 5,
    calories: 275,
    protein: 27,
    carbs: 39,
    fat: 3,
    fiber: 6,
    equipment: ["Thermomix", "blender"],
    ingredients: [
      "1 very ripe persimmon, about 180 g flesh",
      "150 g soy yogurt or skyr",
      "20 g vanilla protein powder",
      "1/2 tsp vanilla",
      "Pinch salt"
    ],
    steps: [
      "Remove persimmon stem and any seeds.",
      "Thermomix: blend all ingredients 30 sec/speed 8, scrape down, then 15 sec/speed 8. Blender: blend until completely smooth.",
      "Chill 20–30 minutes if you want a firmer mousse."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "dense-hipro-bowl",
    title: "Cheesecake HiPro Yogurt Bowl",
    emoji: "🥣",
    description: "Very thick cheesecake-style protein yogurt bowl.",
    category: "snack",
    tags: ["sweet", "high protein", "quick"],
    servings: 1,
    time: 5,
    calories: 320,
    protein: 38,
    carbs: 31,
    fat: 6,
    fiber: 4,
    equipment: [],
    ingredients: [
      "250 g HiPro or high-protein yogurt",
      "20 g vanilla protein powder",
      "10 g chia seeds",
      "80 g berries",
      "10 g crushed biscuits or oats",
      "Vanilla and sweetener",
      "Pinch salt"
    ],
    steps: [
      "Stir yogurt, protein powder, vanilla, sweetener and salt until smooth.",
      "Mix in chia and let stand 5 minutes to thicken.",
      "Top with berries and crushed biscuits/oats."
    ],
    note: "Approximate macros per bowl."
  },
  {
    id: "quick-chia-pudding",
    title: "Five-Minute Warm Chia Pudding",
    emoji: "🌱",
    description: "Fast microwave chia pudding with yogurt and fruit.",
    category: "breakfast",
    tags: ["sweet", "quick", "vegetarian", "snack"],
    servings: 1,
    time: 7,
    calories: 300,
    protein: 32,
    carbs: 28,
    fat: 9,
    fiber: 13,
    equipment: ["microwave"],
    ingredients: [
      "25 g chia seeds",
      "180 ml water",
      "150 g skyr or soy yogurt",
      "100 g berries",
      "20 g protein powder",
      "Pinch of salt",
      "Vanilla or cinnamon optional"
    ],
    steps: [
      "Mix chia and water in a large microwave-safe bowl.",
      "Microwave 45 seconds, stir thoroughly, rest 1 minute.",
      "Microwave another 30–45 seconds and stir again. Let stand 2 minutes to thicken.",
      "Stir in yogurt after heating and top with fruit, sweetener and spice."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "pumpkin-peanut-soup",
    title: "Thai-ish Pumpkin Peanut Soup",
    emoji: "🎃",
    description: "Creamy pumpkin soup with peanut, ginger and lime.",
    category: "main",
    tags: ["vegetarian", "Thermomix", "comfort"],
    servings: 2,
    time: 30,
    calories: 390,
    protein: 18,
    carbs: 47,
    fat: 16,
    fiber: 11,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "500 g pumpkin, cubed",
      "150 g carrots",
      "100 g red lentils, rinsed",
      "650 ml vegetable stock",
      "30 g peanut butter",
      "100 ml light coconut milk or soy milk",
      "15 g soy sauce",
      "10 g ginger",
      "1 garlic clove",
      "1 lime"
    ],
    steps: [
      "Thermomix: add garlic and ginger; chop 5 sec/speed 7. Add pumpkin, carrot, lentils and stock.",
      "Cook 20 min/100°C/speed 1.",
      "Add peanut butter, milk and soy sauce; blend 1 min gradually speed 5–9.",
      "Add lime juice and blend 10 sec/speed 4. Adjust thickness with hot water.",
      "Hob option: simmer pumpkin, carrot and lentils 20–25 minutes, then blend and stir in remaining ingredients."
    ],
    note: "Approximate macros per serving; makes 2."
  },
  {
    id: "pumpkin-pasta",
    title: "Creamy Pumpkin Pasta",
    emoji: "🎃",
    description: "Creamy pumpkin-parmesan pasta with cottage cheese.",
    category: "main",
    tags: ["vegetarian", "pasta", "Thermomix", "high protein"],
    servings: 1,
    time: 25,
    calories: 520,
    protein: 29,
    carbs: 76,
    fat: 12,
    fiber: 10,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "75 g dry pasta",
      "220 g cooked pumpkin",
      "100 g cottage cheese",
      "100 ml stock or milk",
      "15 g parmesan",
      "1 garlic clove",
      "1/4 tsp nutmeg",
      "Salt, pepper and sage optional"
    ],
    steps: [
      "Cook pasta and reserve 100 ml pasta water.",
      "Thermomix: add pumpkin, cottage cheese, stock/milk, parmesan, garlic and nutmeg; blend 45 sec/speed 8.",
      "Warm 4 min/90°C/speed 2.",
      "Toss sauce with pasta and enough pasta water to coat smoothly. Season and add sage if using."
    ],
    note: "Approximate macros per serving; change pasta for lentil pasta for higher protein."
  },
  {
    id: "lentil-spekjes-chorizo-stew",
    title: "Lentil & Chorizo Stew",
    emoji: "🥘",
    description: "Comforting lentil spanish-style stew, with Anna's spin.",
    category: "main",
    tags: ["high protein", "comfort", "one pot"],
    servings: 1,
    time: 30,
    calories: 560,
    protein: 33,
    carbs: 55,
    fat: 23,
    fiber: 16,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "260 g canned lentils, drained",
      "100 g Vivera spekjes",
      "20 g chorizo, diced",
      "100 g carrot",
      "100 g bell pepper",
      "80 g onion",
      "200 g chopped tomatoes",
      "5 g olive oil",
      "250 ml stock",
      "1 tsp smoked paprika",
      "1 garlic clove"
    ],
    steps: [
      "Thermomix: add onion, carrot, pepper and garlic; chop 5 sec/speed 5. Add oil and sauté 5 min/120°C/reverse/speed spoon.",
      "Add tomatoes, stock, paprika and chorizo; cook 10 min/100°C/reverse/speed spoon.",
      "Add lentils and Vivera spekjes; cook 7 min/100°C/reverse/speed spoon, measuring cup off.",
      "Hob option: sauté vegetables in oil, add tomatoes/stock/chorizo and simmer 10 minutes, then add lentils and spekjes for 7–8 minutes.",
      "Adjust thickness with water and season."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "truffle-mac-cheese",
    title: "One-Pot Truffle Mac & Cheese",
    emoji: "🧀",
    description: "Creamy truffle mac with vegan mince, Dijon and goat cheese.",
    category: "main",
    tags: ["high protein", "pasta", "comfort", "one pot", "post-workout"],
    servings: 1,
    time: 25,
    calories: 650,
    protein: 38,
    carbs: 74,
    fat: 23,
    fiber: 8,
    equipment: ["hob"],
    ingredients: [
      "75 g dry macaroni",
      "100 g Vivera mince or spekjes",
      "150 g zucchini/mushrooms",
      "25 g goat cheese",
      "15 g parmesan",
      "25 g Dijon mustard",
      "10 g truffle mayo",
      "350 ml water or light stock",
      "Black pepper"
    ],
    steps: [
      "Brown Vivera and vegetables in a non-stick pot for 5–6 minutes.",
      "Add macaroni and 300 ml water/stock. Simmer uncovered, stirring often, until pasta is tender; add more water if needed.",
      "Lower heat and stir in Dijon, goat cheese and parmesan until creamy.",
      "Take off heat and swirl in truffle mayo. Add black pepper and a splash of water if too thick."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "banana-oat-protein-pancakes",
    title: "Banana Oat Protein Pancakes",
    emoji: "🥞",
    description: "Fluffy banana-oat pancakes with protein powder and chia.",
    category: "breakfast",
    tags: ["sweet", "high protein"],
    servings: 1,
    time: 20,
    calories: 480,
    protein: 31,
    carbs: 58,
    fat: 14,
    fiber: 10,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "50 g oats",
      "100 g banana",
      "25 g protein powder",
      "1 egg",
      "10 g chia seeds",
      "100 ml semi-skimmed milk",
      "4 g baking powder",
      "Cinnamon and pinch salt"
    ],
    steps: [
      "Thermomix: add oats and mill 10 sec/speed 9. Add remaining ingredients and blend 20 sec/speed 5.",
      "Let batter rest 5 minutes; pea protein and chia will thicken it. Add 1–2 tbsp water if it becomes too stiff.",
      "Heat a non-stick pan over medium-low heat. Spoon in 4–5 small pancakes.",
      "Cook 2–3 minutes until bubbles appear and edges set, flip, then cook 1–2 minutes more."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "halloumi-potato-shawarma-bowl",
    title: "Halloumi & Shawarma Potato Bowl",
    emoji: "🥔",
    description: "Crispy potatoes with halloumi, vegan shawarma and parmesan yogurt sauce.",
    category: "main",
    tags: ["vegetarian", "high protein", "bowl", "air fryer"],
    servings: 1,
    time: 30,
    calories: 540,
    protein: 31,
    carbs: 51,
    fat: 23,
    fiber: 8,
    equipment: ["air fryer"],
    ingredients: [
      "220 g potatoes, cubed",
      "80 g Vivera shawarma",
      "60 g halloumi",
      "150 g mixed vegetables",
      "80 g yogurt/skyr",
      "10 g parmesan",
      "5 g olive oil",
      "Lemon juice",
      "Garlic powder and pepper"
    ],
    steps: [
      "Preheat air fryer to 195°C. Toss potatoes with oil and seasoning; cook 12 minutes.",
      "Add vegetables and air-fry 5 minutes.",
      "Add Vivera and halloumi and air-fry another 6–8 minutes, shaking halfway.",
      "Mix yogurt, parmesan, lemon and garlic powder.",
      "Build bowl and spoon over sauce."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "kimchi-cheese-pasta",
    title: "Cheesy Kimchi Pasta",
    emoji: "🍝",
    description: "Creamy, savoury kimchi pasta with high-protein mince.",
    category: "main",
    tags: ["high protein", "pasta", "comfort"],
    servings: 1,
    time: 20,
    calories: 590,
    protein: 38,
    carbs: 71,
    fat: 18,
    fiber: 7,
    equipment: ["hob"],
    ingredients: [
      "70 g dry pasta",
      "120 g lean beef or plant mince",
      "80 g kimchi",
      "120 g zucchini or mushrooms",
      "25 g mozzarella",
      "10 g parmesan",
      "5 g sesame oil or olive oil",
      "80 ml pasta water"
    ],
    steps: [
      "Cook pasta and reserve pasta water.",
      "Brown mince in oil for 4–5 minutes. Add vegetables and cook until softened.",
      "Add kimchi and cook 1 minute.",
      "Lower heat, add pasta, mozzarella, parmesan and 50 ml pasta water. Toss until glossy and creamy.",
      "Add more pasta water if needed and serve immediately."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "vivera-shawarma-lentil-salad",
    title: "Vivera Shawarma Lentil Salad",
    emoji: "🥗",
    description: "Warm lentil salad with shawarma and yogurt-tahini dressing.",
    category: "main",
    tags: ["vegetarian", "high protein", "bowl"],
    servings: 1,
    time: 20,
    calories: 510,
    protein: 33,
    carbs: 52,
    fat: 18,
    fiber: 15,
    equipment: ["hob", "air fryer optional"],
    ingredients: [
      "180 g cooked lentils",
      "120 g Vivera shawarma",
      "200 g cucumber, tomato and greens",
      "80 g magere kwark/skyr",
      "12 g tahini",
      "1/2 lemon",
      "5 g olive oil",
      "Herbs, salt and pepper"
    ],
    steps: [
      "Air-fry Vivera at 190°C for 6–8 minutes or brown in a pan.",
      "Warm lentils briefly or leave cold.",
      "Whisk kwark, tahini, lemon, salt and 1–2 tbsp water into a dressing.",
      "Combine lentils and vegetables, top with shawarma and dressing."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "gyoza-casserole",
    title: "Creamy Gyoza Vegetable Bake",
    emoji: "🥟",
    description: "Gyoza baked with vegetables in a savoury creamy sauce.",
    category: "main",
    tags: ["comfort", "quick"],
    servings: 1,
    time: 30,
    calories: 540,
    protein: 22,
    carbs: 65,
    fat: 21,
    fiber: 9,
    equipment: ["oven", "air fryer optional"],
    ingredients: [
      "8 vegetable or chicken gyoza, about 200 g",
      "200 g mixed vegetables",
      "100 ml light cooking cream or soy cuisine",
      "15 g soy sauce",
      "10 g miso",
      "50 ml water",
      "10 g grated cheese",
      "Spring onion"
    ],
    steps: [
      "Heat oven to 200°C. Air-fryer casserole option: use a heatproof dish at 180°C.",
      "Arrange gyoza and vegetables in a small baking dish.",
      "Whisk cream, soy sauce, miso and water; pour over.",
      "Top with cheese. Bake 20–25 minutes in oven or 15–18 minutes in air fryer until bubbling and gyoza are cooked.",
      "Finish with spring onion."
    ],
    note: "Approximate macros depend on gyoza brand."
  },
  {
    id: "alpro-vanilla-yogurt-muffins",
    title: "Vanilla Yogurt Protein Muffins",
    emoji: "🧁",
    description: "Soft muffins using vanilla yogurt, whole-wheat flour and protein powder.",
    category: "snack",
    tags: ["sweet", "meal prep", "high protein"],
    servings: 6,
    time: 30,
    calories: 155,
    protein: 9,
    carbs: 22,
    fat: 4,
    fiber: 3,
    equipment: ["oven", "air fryer optional", "Thermomix optional"],
    ingredients: [
      "180 g Alpro vanilla yogurt",
      "120 g whole-wheat flour",
      "50 g protein powder",
      "2 eggs",
      "80 g banana or applesauce",
      "60 ml milk",
      "8 g baking powder",
      "1 tsp vanilla",
      "Pinch salt"
    ],
    steps: [
      "Thermomix: add wet ingredients and mix 15 sec/speed 4. Add dry ingredients and mix 12 sec/speed 4. Otherwise whisk by hand.",
      "Divide among 6 muffin cups.",
      "Bake at 180°C for 18–20 minutes, or air-fry at 160°C for 12–14 minutes.",
      "Cool before storing."
    ],
    note: "Approximate macros per muffin."
  },
  {
    id: "quick-pre-gym-protein-oats",
    title: "Quick Pre-Gym Protein Oats",
    emoji: "🥣",
    description: "Fast microwave oats with chia and protein powder.",
    category: "breakfast",
    tags: ["sweet", "high protein", "quick"],
    servings: 1,
    time: 5,
    calories: 330,
    protein: 25,
    carbs: 39,
    fat: 8,
    fiber: 8,
    equipment: ["microwave"],
    ingredients: [
      "30 g oats",
      "10 g chia seeds",
      "25 g protein powder",
      "180 ml water or milk",
      "Optional 5 g coconut flakes",
      "Pinch salt"
    ],
    steps: [
      "Mix oats, chia, salt and liquid in a large microwave-safe bowl.",
      "Microwave 90 seconds, stir, then microwave 30–60 seconds more.",
      "Let stand 1 minute.",
      "Stir in protein powder; add a splash more liquid until creamy. Add coconut if using."
    ],
    note: "Approximate macros with water and coconut omitted; milk/toppings increase them."
  },
  {
    id: "cucumber-tuna-crunch-salad",
    title: "Cucumber Tuna Crunch Salad",
    emoji: "🥒",
    description: "Cold tuna, cucumber, edamame and sesame-tahini salad.",
    category: "main",
    tags: ["high protein", "quick", "bowl"],
    servings: 1,
    time: 10,
    calories: 430,
    protein: 34,
    carbs: 35,
    fat: 18,
    fiber: 9,
    equipment: [],
    ingredients: [
      "100 g tuna, drained",
      "200 g cucumber",
      "75 g edamame",
      "40 g avocado",
      "40 g cooked rice or quinoa",
      "5 g sesame seeds",
      "10 g tahini",
      "10 g soy sauce",
      "10 g rice vinegar or lime juice",
      "Spring onion",
      "15–25 ml water"
    ],
    steps: [
      "Dice cucumber and avocado; slice spring onion.",
      "Whisk tahini, soy sauce, vinegar/lime and water until creamy.",
      "Combine cucumber, edamame and rice/quinoa.",
      "Flake tuna over the bowl, add avocado, dressing, sesame and spring onion."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "burrata-tomato-pesto-tuna",
    title: "Burrata, Tomato, Pesto & Tuna",
    emoji: "🍅",
    description: "Tomatoes, creamy burrata, tuna, pesto and toasted bread.",
    category: "main",
    tags: ["high protein", "quick", "summer"],
    servings: 1,
    time: 10,
    calories: 440,
    protein: 35,
    carbs: 31,
    fat: 20,
    fiber: 5,
    equipment: ["air fryer optional"],
    ingredients: [
      "60 g burrata",
      "100 g tuna, drained",
      "250 g tomatoes",
      "10 g pesto",
      "40 g sourdough or crusty bread",
      "Rocket or basil",
      "Balsamic vinegar",
      "Black pepper"
    ],
    steps: [
      "Air-fry or toast bread at 180°C for 4–5 minutes until crisp.",
      "Slice tomatoes and arrange with rocket/basil.",
      "Flake tuna over the tomatoes and tear burrata on top.",
      "Spoon over pesto, add balsamic and black pepper. Serve with toast."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "koolvis-potato-soup",
    title: "Koolvis & Potato Soup",
    emoji: "🐟",
    description: "Light creamy pollock soup with potato, leek, peas and dill.",
    category: "main",
    tags: ["high protein", "soup", "comfort", "Thermomix"],
    servings: 1,
    time: 30,
    calories: 430,
    protein: 38,
    carbs: 48,
    fat: 10,
    fiber: 9,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "150 g koolvis/pollock, cubed",
      "150 g potato, 2 cm cubes",
      "100 g leek",
      "100 g carrot",
      "75 g peas",
      "75 ml semi-skimmed milk",
      "350 ml fish or vegetable stock",
      "3 g olive oil",
      "Dill",
      "Lemon juice",
      "Black pepper"
    ],
    steps: [
      "Thermomix: add leek and carrot; chop 5 sec/speed 5. Add oil; sauté 4 min/120°C/reverse/speed spoon.",
      "Add potato and stock; cook 14 min/100°C/reverse/speed spoon.",
      "Add peas and fish; cook 6 min/90°C/reverse/speed spoon.",
      "Add milk, dill, lemon and pepper; warm 2 min/80°C/reverse/speed spoon.",
      "Hob option: follow the same order, simmering gently so the fish does not break up."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "miso-tofu-noodle-soup",
    title: "Miso Tofu Noodle Soup",
    emoji: "🍜",
    description: "Brothy miso noodles with tofu, edamame, mushrooms and greens.",
    category: "main",
    tags: ["vegetarian", "high protein", "soup", "quick", "Thermomix"],
    servings: 1,
    time: 20,
    calories: 440,
    protein: 29,
    carbs: 55,
    fat: 13,
    fiber: 10,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "125 g firm tofu, cubed",
      "45 g dry noodles",
      "75 g edamame",
      "150 g mushrooms",
      "150 g pak choi/spinach",
      "20 g white miso",
      "10 g soy sauce",
      "3 g sesame oil",
      "10 g ginger",
      "500 ml vegetable stock",
      "Spring onion"
    ],
    steps: [
      "Thermomix: add ginger and chop 5 sec/speed 7. Add stock and mushrooms; cook 7 min/100°C/reverse/speed spoon.",
      "Add noodles, tofu and edamame; cook for the noodle packet time at 100°C/reverse/speed spoon.",
      "Add greens for the final 1–2 minutes.",
      "Let cool to about 80–90°C. Mix miso with a little broth in a cup, then stir it back in with soy sauce and sesame oil.",
      "Finish with spring onion. Hob option: use the same order in a saucepan."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "stuffed-aubergine-vivera",
    title: "Stuffed Aubergine",
    emoji: "🍆",
    description: "Roasted aubergine stuffed with Vivera mince, tomato, feta and parmesan.",
    category: "main",
    tags: ["vegetarian", "high protein", "comfort", "air fryer"],
    servings: 1,
    time: 35,
    calories: 450,
    protein: 33,
    carbs: 35,
    fat: 21,
    fiber: 12,
    equipment: ["air fryer", "oven optional"],
    ingredients: [
      "1 medium aubergine, about 300 g",
      "120 g Vivera mince",
      "80 g onion",
      "100 g courgette or pepper",
      "100 g tomato sauce",
      "20 g feta",
      "10 g parmesan",
      "3 g olive oil",
      "Italian herbs, salt and pepper"
    ],
    steps: [
      "Halve aubergine and score the flesh. Brush with oil and air-fry cut-side up at 190°C for 12 minutes.",
      "Scoop out some flesh, leaving a 1 cm shell; chop the flesh.",
      "Cook Vivera, onion and courgette in a pan 5–6 minutes. Add aubergine flesh, tomato sauce and herbs; simmer 3 minutes.",
      "Fill the aubergine shells, crumble feta and parmesan over them.",
      "Air-fry at 190°C for 7–9 minutes until browned."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "satay-veg-rice-bowl",
    title: "Satay Veg & Rice Bowl",
    emoji: "🥜",
    description: "Rice, vegetables and protein with a lime-peanut satay sauce.",
    category: "main",
    tags: ["high protein", "bowl"],
    servings: 1,
    time: 25,
    calories: 560,
    protein: 35,
    carbs: 67,
    fat: 18,
    fiber: 9,
    equipment: ["hob", "air fryer optional", "Thermomix optional"],
    ingredients: [
      "60 g dry rice",
      "150 g tofu or 120 g chicken",
      "250 g mixed vegetables",
      "15 g peanut butter",
      "12 g soy sauce",
      "1/2 lime",
      "5 g honey",
      "5 g oil",
      "Garlic and ginger",
      "30–50 ml hot water"
    ],
    steps: [
      "Cook rice.",
      "Air-fryer protein option: cook tofu/chicken and vegetables at 195°C for 10–14 minutes, tossing with oil and seasoning; ensure chicken is cooked through.",
      "Thermomix sauce: add peanut butter, soy, lime, honey, garlic, ginger and water; mix 20 sec/speed 5, then warm 2 min/70°C/speed 2. Or whisk by hand.",
      "Serve rice with vegetables and protein and spoon over satay sauce."
    ],
    note: "Approximate macros per serving; tofu/chicken will shift them slightly."
  },
  {
    id: "summer-spring-rolls-peanut-dip",
    title: "Summer Spring Rolls with Peanut Dip",
    emoji: "🌿",
    description: "Fresh rice-paper rolls with vermicelli, vegetables and protein.",
    category: "main",
    tags: ["high protein", "summer", "fresh"],
    servings: 1,
    time: 30,
    calories: 540,
    protein: 30,
    carbs: 72,
    fat: 16,
    fiber: 8,
    equipment: ["hob"],
    ingredients: [
      "5 rice-paper sheets",
      "50 g dry rice vermicelli",
      "150 g prawns or tofu",
      "100 g cucumber",
      "80 g carrot",
      "60 g lettuce",
      "Fresh mint/coriander",
      "50 g mango optional",
      "20 g peanut butter",
      "10 g soy sauce",
      "1/2 lime",
      "20–30 ml water"
    ],
    steps: [
      "Cook vermicelli according to packet, rinse cold and drain well.",
      "Cook prawns or tofu and cool slightly.",
      "Cut vegetables into thin matchsticks.",
      "Whisk peanut butter, soy sauce, lime and water into a dip.",
      "Dip one rice-paper sheet in warm water for 5–10 seconds. Fill with noodles, protein, vegetables and herbs, fold sides inward and roll tightly.",
      "Repeat and serve immediately with peanut dip."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "classic-cheeseburger",
    title: "Classic Cheeseburger",
    emoji: "🍔",
    description: "A proper cheeseburger with pickles, sauce and crispy wedges.",
    category: "main",
    tags: ["high protein", "comfort"],
    servings: 1,
    time: 30,
    calories: 580,
    protein: 38,
    carbs: 57,
    fat: 22,
    fiber: 6,
    equipment: ["air fryer", "hob"],
    ingredients: [
      "1 burger bun, about 70 g",
      "120 g lean beef patty",
      "20 g cheese slice",
      "100 g potatoes, cut into wedges",
      "Lettuce, tomato, pickles and red onion",
      "10 g light mayo",
      "5 g ketchup",
      "5 g mustard",
      "3 g olive oil",
      "Salt and pepper"
    ],
    steps: [
      "Preheat air fryer to 195°C. Toss wedges with oil and salt; air-fry 15–18 minutes, shaking twice.",
      "Season patty and cook in a hot pan 3–4 minutes per side, or until cooked to preference. Add cheese for the final minute.",
      "Mix mayo, ketchup and mustard.",
      "Toast bun cut-side down in the pan for 1 minute.",
      "Assemble bun, sauce, lettuce, tomato, patty, pickles and onion. Serve with wedges."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "high-protein-lasagna",
    title: "High-Protein Lasagna",
    emoji: "🍅",
    description: "Rich ragù, pasta sheets, béchamel and cheese in a meal-prep lasagna.",
    category: "main",
    tags: ["high protein", "comfort", "meal prep", "pasta"],
    servings: 4,
    time: 75,
    calories: 580,
    protein: 38,
    carbs: 58,
    fat: 21,
    fiber: 8,
    equipment: ["oven", "Thermomix optional"],
    ingredients: [
      "500 g lean beef mince or Vivera mince",
      "240 g dry lasagna sheets",
      "500 g passata",
      "150 g onion",
      "150 g carrot",
      "150 g courgette",
      "10 g olive oil",
      "400 ml semi-skimmed milk",
      "30 g flour",
      "20 g butter",
      "100 g mozzarella",
      "40 g parmesan",
      "Italian herbs, salt and pepper"
    ],
    steps: [
      "Thermomix veg prep: chop onion, carrot and courgette 5 sec/speed 5. Sauté with oil 5 min/120°C/reverse/speed spoon. Add mince and cook 7 min/120°C/reverse/speed spoon. Add passata/herbs and simmer 12 min/100°C/reverse/speed spoon. Or make ragù in a pan.",
      "Béchamel Thermomix: add milk, flour, butter, salt and pepper; cook 7 min/90°C/speed 4.",
      "Heat oven to 190°C.",
      "Layer ragù, lasagna sheets and béchamel in a medium baking dish, repeating until used.",
      "Top with mozzarella and parmesan. Bake 35–40 minutes until bubbling and browned.",
      "Rest 10 minutes, then cut into 4 portions."
    ],
    note: "Approximate macros per 1/4 tray."
  },
  {
    id: "protein-snickers-bars",
    title: "High-Protein Snickers Bars",
    emoji: "🍫",
    description: "Chewy peanut-caramel protein bars with chocolate and flaky salt.",
    category: "snack",
    tags: ["sweet", "high protein", "meal prep"],
    servings: 6,
    time: 30,
    calories: 195,
    protein: 13,
    carbs: 22,
    fat: 7,
    fiber: 3,
    equipment: ["Thermomix", "fridge"],
    ingredients: [
      "70 g oat flour",
      "90 g vanilla protein powder",
      "100 g soft dates",
      "35 g peanut butter",
      "30 g roasted peanuts, chopped",
      "50 g dark chocolate",
      "80 ml milk, divided",
      "1 tsp vanilla",
      "Pinch flaky salt"
    ],
    steps: [
      "Thermomix base: add oat flour, 70 g protein powder, vanilla and 45 ml milk; mix 20 sec/speed 4. Press into a lined loaf tin.",
      "Add dates, peanut butter and 25 ml milk; blend 25 sec/speed 7, scrape down, then 10 sec/speed 7. Spread over base.",
      "Press chopped peanuts into the caramel.",
      "Melt chocolate in microwave in 20-second bursts or Thermomix 3 min/50°C/speed 2. Spread a thin layer over the top and add flaky salt.",
      "Chill 1–2 hours, then cut into 6 bars."
    ],
    note: "Approximate macros per bar."
  },
  {
    id: "loaded-protein-pita",
    title: "Loaded Protein Pita",
    emoji: "🥙",
    description: "Warm pita with protein, crunchy salad, feta and yogurt-tahini sauce.",
    category: "main",
    tags: ["high protein", "quick"],
    servings: 1,
    time: 20,
    calories: 450,
    protein: 32,
    carbs: 48,
    fat: 15,
    fiber: 8,
    equipment: ["air fryer", "hob"],
    ingredients: [
      "1 pita, about 65 g",
      "110 g chicken or Vivera shawarma",
      "150 g cucumber/tomato/lettuce",
      "20 g feta",
      "60 g skyr or yogurt",
      "8 g tahini",
      "1/2 lemon",
      "1 small garlic clove",
      "Salt, pepper and herbs"
    ],
    steps: [
      "Air-fry chicken/Vivera at 190°C until browned and cooked; chicken usually needs 10–12 minutes, Vivera 6–8.",
      "Mix yogurt, tahini, grated garlic, lemon and a splash of water.",
      "Warm pita in air fryer at 160°C for 2 minutes.",
      "Fill with salad, protein, feta and sauce."
    ],
    note: "Approximate macros per serving."
  },
  {
    id: "salmon-brussels-potatoes",
    title: "Salmon, Brussels Sprouts & Potatoes",
    emoji: "🐟",
    description: "Roasted salmon with crispy Brussels, potatoes and lemon-Dijon yogurt.",
    category: "main",
    tags: ["high protein", "air fryer"],
    servings: 1,
    time: 35,
    calories: 500,
    protein: 32,
    carbs: 47,
    fat: 21,
    fiber: 11,
    equipment: ["air fryer"],
    ingredients: [
      "120 g salmon fillet",
      "180 g potatoes, cubed",
      "200 g Brussels sprouts, halved",
      "3 g olive oil",
      "1 tbsp hoisin sauce",
      "1 tsp honey",
      "1 tsp soy sauce",
      "Garlic powder, ginger, salt and pepper"
    ],
    steps: [
      "Preheat air fryer to 195°C. Toss potatoes and Brussels with oil and seasoning; air-fry 12 minutes, shaking once.",
      "Push vegetables aside and add seasoned salmon. Air-fry another 8–10 minutes, depending on thickness.",
      "Mix yogurt, Dijon, lemon juice and a pinch of garlic powder.",
      "Serve salmon with crispy vegetables and sauce."
    ],
    note: "Approximate macros per serving. Add cheese or nuts  for extra fat"
  },
  {
    id: "judias-verdes-con-tomate",
    title: "Judías Verdes con Tomate",
    emoji: "🫛",
    description: "Spanish-style green beans braised with tomato, onion and garlic.",
    category: "side",
    tags: ["vegetarian", "meal prep", "high fibre", "Thermomix"],
    servings: 4,
    time: 35,
    calories: 175,
    protein: 5,
    carbs: 22,
    fat: 7,
    fiber: 8,
    equipment: ["Thermomix", "hob"],
    ingredients: [
      "800 g green beans, trimmed",
      "500 g crushed tomatoes/passata",
      "180 g onion",
      "3 garlic cloves",
      "20 g olive oil",
      "1 tsp sweet or smoked paprika",
      "100 ml water",
      "Salt and pepper"
    ],
    steps: [
      "Thermomix: add onion and garlic; chop 5 sec/speed 5. Add oil and sauté 5 min/120°C/speed 1.",
      "Add tomato, paprika, salt and pepper; cook 8 min/100°C/speed 1.",
      "Add green beans and water; cook 20–25 min/100°C/reverse/speed spoon, measuring cup off for the last 8 minutes if too watery.",
      "Hob option: sauté onion/garlic, add tomato 8 minutes, then beans and water; cover and simmer until tender.",
      "Divide into 4 portions."
    ],
    note: "Approximate macros per 1/4 batch."
  },
  {
    id: "creamy-salmon-gnocchi",
    title: "Creamy Salmon Gnocchi",
    emoji: "🍝",
    description: "Pillowy gnocchi and salmon in a lemon-parmesan cream sauce.",
    category: "main",
    tags: ["high protein", "comfort", "quick"],
    servings: 1,
    time: 25,
    calories: 630,
    protein: 34,
    carbs: 73,
    fat: 24,
    fiber: 7,
    equipment: ["hob"],
    ingredients: [
      "200 g fresh gnocchi",
      "100 g salmon",
      "100 g spinach",
      "50 g peas",
      "50 ml cooking cream",
      "10 g parmesan",
      "1 small garlic clove",
      "1/2 lemon, zest and juice",
      "Dill",
      "Black pepper"
    ],
    steps: [
      "Boil gnocchi until they float; reserve 80 ml cooking water and drain.",
      "Pan-sear salmon over medium heat until just cooked, then remove and flake into large pieces.",
      "In the same pan cook garlic 30 seconds, then add peas and spinach until wilted.",
      "Lower heat and stir in cream, parmesan, lemon zest and 30 ml cooking water.",
      "Add gnocchi and salmon, toss gently for 1–2 minutes, and loosen with more water if needed.",
      "Finish with lemon juice, dill and black pepper."
    ],
    note: "Approximate macros per serving."
  },
  {
  id: "ramen",
  title: "Miso Tofu Egg Ramen",
  emoji: "🍜",
  description: "Cozy miso ramen with tofu, egg, mushrooms and greens.",
  category: "main",
  tags: ["high protein", "comfort food", "quick"],
  servings: 1,
  time: 20,
  calories: 525,
  protein: 31,
  carbs: 62,
  fat: 18,
  fiber: 8,
  equipment: ["hob"],
  ingredients: [
    "70 g ramen noodles",
    "120 g firm tofu, cubed",
    "1 egg",
    "100 g mushrooms",
    "100 g pak choi",
    "15 g miso paste",
    "8 g peanut butter",
    "1 tsp soy sauce",
    "400 ml vegetable stock",
    "Garlic and ginger"
  ],
  steps: [
    "Sauté mushrooms, garlic and ginger until fragrant.",
    "Add stock, miso and soy sauce and bring to a gentle simmer.",
    "Add tofu, pak choi and noodles; cook until tender.",
    "Stir peanut butter into the broth until creamy.",
    "Top with a soft-boiled egg."
  ]
},

{
  id: "kimchi-risotto",
  title: "Kimchi Edamame Risotto",
  emoji: "🍚",
  description: "Creamy savoury risotto with kimchi and parmesan.",
  category: "main",
  tags: ["high protein", "vegetarian", "comfort food", "meal prep"],
  servings: 1,
  time: 30,
  calories: 505,
  protein: 25,
  carbs: 68,
  fat: 15,
  fiber: 8,
  equipment: ["hob"],
  ingredients: [
    "70 g risotto rice",
    "100 g kimchi",
    "15 g parmesan",
    "5 g sesame oil",
    "50 g onion",
    "1 garlic clove",
    "400 ml vegetable stock",
    "1 tsp soy sauce"
  ],
  steps: [
    "Sauté onion and garlic until soft.",
    "Add rice and toast for 1–2 minutes.",
    "Gradually add hot stock while stirring.",
    "Stir in kimchi and edamame during the final 5 minutes.",
    "Finish with parmesan, sesame oil and soy sauce."
  ]
},

{
  id: "feta-chickpea-tuna-salad",
  title: "Feta Chickpea Tuna Salad",
  emoji: "🥗",
  description: "Fresh lemony chickpea salad with tuna, feta and crunchy vegetables.",
  category: "main",
  tags: ["high protein", "high fibre", "meal prep", "quick"],
  servings: 1,
  time: 10,
  calories: 480,
  protein: 38,
  carbs: 43,
  fat: 17,
  fiber: 11,
  equipment: ["none"],
  ingredients: [
    "120 g chickpeas, drained",
    "80 g tuna, drained",
    "40 g feta",
    "100 g cucumber",
    "50 g roasted pepper",
    "30 g red onion",
    "5 g olive oil",
    "Juice of 1/2 lemon",
    "Parsley",
    "Salt and pepper"
  ],
  steps: [
    "Chop the vegetables and add them to a bowl.",
    "Add chickpeas, tuna and crumbled feta.",
    "Dress with olive oil, lemon, parsley, salt and pepper.",
    "Toss everything together and serve."
  ]
},

{
  id: "meatballs-rice-tomato",
  title: "Meatballs with Rice & Tomato",
  emoji: "🍅",
  description: "Juicy meatballs with rice and a rich garlicky tomato sauce.",
  category: "main",
  tags: ["high protein", "meal prep", "comfort food"],
  servings: 1,
  time: 30,
  calories: 520,
  protein: 34,
  carbs: 64,
  fat: 14,
  fiber: 7,
  equipment: ["hob", "airfryer"],
  ingredients: [
    "120 g lean meatballs",
    "65 g dry rice",
    "150 g passata",
    "100 g courgette",
    "50 g onion",
    "5 g olive oil",
    "1 garlic clove",
    "Italian herbs",
    "Salt and pepper"
  ],
  steps: [
    "Cook rice according to package instructions.",
    "Cook meatballs until browned and cooked through.",
    "Sauté onion, garlic and courgette in olive oil.",
    "Add passata and herbs and simmer for 10 minutes.",
    "Add the meatballs to the sauce and serve with rice."
  ]
},

{
  id: "truffle-carbonara-spekjes",
  title: "Truffle Carbonara with Spekjes",
  emoji: "🍝",
  description: "Silky truffle carbonara with smoky spekjes, egg and parmesan.",
  category: "main",
  tags: ["high protein", "pasta", "truffle", "comfort food"],
  servings: 1,
  time: 20,
  calories: 495,
  protein: 34,
  carbs: 57,
  fat: 15,
  fiber: 6,
  equipment: ["hob"],
  ingredients: [
    "75 g pasta",
    "80 g spekjes",
    "1 egg",
    "20 g parmesan",
    "1 tsp truffle paste",
    "Black pepper",
    "Reserved pasta water"
  ],
  steps: [
    "Cook pasta until al dente and reserve plenty of pasta water.",
    "Crisp the spekjes in a pan.",
    "Whisk egg, parmesan, truffle paste and black pepper.",
    "Remove the pan from the heat and add the pasta.",
    "Stir through the egg mixture, gradually adding pasta water until glossy and creamy.",
    "Top with the crispy spekjes and extra black pepper."
  ]
},

{
  id: "berenjena-garbanzos-tomate",
  title: "Berenjena, Garbanzos & Tomate",
  emoji: "🍆",
  description: "Soft aubergine, chickpeas and high-protein mince simmered in smoky tomato.",
  category: "main",
  tags: ["high protein", "high fibre", "meal prep"],
  servings: 1,
  time: 30,
  calories: 480,
  protein: 32,
  carbs: 50,
  fat: 16,
  fiber: 15,
  equipment: ["hob"],
  ingredients: [
    "200 g aubergine",
    "120 g chickpeas, drained",
    "100 g vegan mince",
    "150 g passata",
    "60 g onion",
    "5 g olive oil",
    "1 garlic clove",
    "1 tsp smoked paprika",
    "Cumin",
    "Salt and pepper"
  ],
  steps: [
    "Dice the aubergine and cook until golden and soft.",
    "Add onion and garlic and sauté.",
    "Add vegan mince and cook for a few minutes.",
    "Stir in chickpeas, passata and spices.",
    "Simmer for 10–15 minutes until rich and thick."
  ]
},

{
  id: "pimientos-rellenos",
  title: "Pimientos Rellenos",
  emoji: "🫑",
  description: "Roasted peppers stuffed with rice, protein-rich mince and melted mozzarella.",
  category: "main",
  tags: ["high protein", "meal prep", "oven"],
  servings: 1,
  time: 40,
  calories: 485,
  protein: 33,
  carbs: 62,
  fat: 11,
  fiber: 9,
  equipment: ["oven", "hob"],
  ingredients: [
    "2 bell peppers",
    "60 g dry rice",
    "120 g vegan mince",
    "100 g passata",
    "40 g light mozzarella",
    "50 g onion",
    "1 garlic clove",
    "Smoked paprika",
    "Salt and pepper"
  ],
  steps: [
    "Halve the peppers and remove the seeds.",
    "Cook the rice until tender.",
    "Sauté onion and garlic, then add the mince.",
    "Stir in passata, rice and seasonings.",
    "Fill the peppers and top with mozzarella.",
    "Bake at 200°C for 20–25 minutes."
  ]
},

{
  id: "mushroom-risotto",
  title: "Creamy Mushroom Risotto",
  emoji: "🍄",
  description: "Creamy parmesan mushroom risotto with edamame for a little extra protein.",
  category: "main",
  tags: ["vegetarian", "high protein", "comfort food"],
  servings: 1,
  time: 30,
  calories: 510,
  protein: 25,
  carbs: 68,
  fat: 15,
  fiber: 8,
  equipment: ["hob"],
  ingredients: [
    "70 g risotto rice",
    "200 g mushrooms",
    "100 g edamame",
    "15 g parmesan",
    "5 g olive oil",
    "50 g onion",
    "1 garlic clove",
    "400 ml vegetable stock",
    "Thyme",
    "Black pepper"
  ],
  steps: [
    "Brown the mushrooms and set aside.",
    "Sauté onion and garlic in olive oil.",
    "Add rice and toast briefly.",
    "Gradually add stock while stirring.",
    "Add edamame and mushrooms near the end.",
    "Finish with parmesan, thyme and black pepper."
  ]
},

{
  id: "tahini-chickpea-shrimp-pasta",
  title: "Tahini Chickpea Pasta with Shrimp",
  emoji: "🍤",
  description: "Creamy lemon-tahini pasta with chickpeas, courgette and juicy shrimp.",
  category: "main",
  tags: ["high protein", "high fibre", "pasta"],
  servings: 1,
  time: 20,
  calories: 550,
  protein: 40,
  carbs: 66,
  fat: 15,
  fiber: 11,
  equipment: ["hob"],
  ingredients: [
    "65 g pasta",
    "100 g shrimp",
    "80 g chickpeas, drained",
    "15 g tahini",
    "100 g courgette",
    "Juice of 1/2 lemon",
    "1 garlic clove",
    "Reserved pasta water",
    "Parsley",
    "Salt and pepper"
  ],
  steps: [
    "Cook pasta and reserve some pasta water.",
    "Cook shrimp and courgette with garlic.",
    "Whisk tahini, lemon juice and pasta water until creamy.",
    "Add chickpeas and pasta to the pan.",
    "Stir through the tahini sauce and top with shrimp."
  ]
},

{
  id: "hot-honey-chickpea-tofu-bowl",
  title: "Hot Honey Chickpea Tofu Bowl",
  emoji: "🍯",
  description: "Crispy tofu and chickpeas with rice, vegetables and sticky hot honey sauce.",
  category: "main",
  tags: ["high protein", "vegetarian", "bowl", "high fibre"],
  servings: 1,
  time: 25,
  calories: 550,
  protein: 29,
  carbs: 72,
  fat: 17,
  fiber: 12,
  equipment: ["airfryer", "hob"],
  ingredients: [
    "150 g firm tofu",
    "80 g chickpeas, drained",
    "50 g dry rice",
    "150 g mixed vegetables",
    "15 g hot honey",
    "5 g sesame oil",
    "1 tsp soy sauce",
    "Garlic powder",
    "Smoked paprika"
  ],
  steps: [
    "Cook rice according to package instructions.",
    "Season tofu and chickpeas and airfry until crispy.",
    "Cook the vegetables until just tender.",
    "Mix hot honey, sesame oil and soy sauce.",
    "Assemble the bowl and drizzle over the sauce."
  ]
},

{
  id: "pesto-cottage-cheese-sandwich",
  title: "Pesto Cottage Cheese Sandwich",
  emoji: "🥪",
  description: "Golden whole-wheat toast filled with pesto, cottage cheese and melted mozzarella.",
  category: "lunch",
  tags: ["high protein", "quick", "vegetarian"],
  servings: 1,
  time: 10,
  calories: 445,
  protein: 30,
  carbs: 45,
  fat: 16,
  fiber: 7,
  equipment: ["pan", "sandwich press"],
  ingredients: [
    "2 large slices whole-wheat bread",
    "120 g cottage cheese",
    "10 g pesto",
    "30 g light mozzarella",
    "Handful of spinach",
    "Black pepper"
  ],
  steps: [
    "Spread pesto over the whole-wheat bread.",
    "Add cottage cheese, mozzarella and spinach.",
    "Season with black pepper.",
    "Close and toast until golden and the mozzarella has melted."
  ]
},

{
  id: "spinach-omelette",
  title: "Spinach & Feta Omelette",
  emoji: "🍳",
  description: "Fluffy spinach and feta omelette with whole-wheat toast.",
  category: "breakfast",
  tags: ["high protein", "quick", "vegetarian"],
  servings: 1,
  time: 15,
  calories: 460,
  protein: 31,
  carbs: 38,
  fat: 20,
  fiber: 7,
  equipment: ["hob"],
  ingredients: [
    "2 eggs",
    "100 g egg whites",
    "100 g spinach",
    "30 g feta",
    "2 slices whole-wheat bread",
    "5 g olive oil",
    "Salt and pepper"
  ],
  steps: [
    "Wilt the spinach in a pan.",
    "Whisk eggs and egg whites with salt and pepper.",
    "Pour into the pan and cook gently.",
    "Add feta and fold the omelette.",
    "Serve with whole-wheat toast."
  ]
},

{
  id: "mafaldine-al-tartufo",
  title: "Mafaldine al Tartufo",
  emoji: "🍝",
  description: "Silky truffle mafaldine with golden mushrooms and parmesan.",
  category: "main",
  tags: ["high protein", "pasta", "truffle", "comfort food"],
  servings: 1,
  time: 20,
  calories: 525,
  protein: 28,
  carbs: 65,
  fat: 18,
  fiber: 7,
  equipment: ["hob"],
  ingredients: [
    "75 g mafaldine",
    "150 g mushrooms",
    "80 g cottage cheese",
    "20 g parmesan",
    "1 tsp truffle paste",
    "5 g olive oil",
    "1 garlic clove",
    "Reserved pasta water",
    "Black pepper"
  ],
  steps: [
    "Cook mafaldine until al dente and reserve pasta water.",
    "Brown mushrooms with olive oil and garlic.",
    "Blend cottage cheese, parmesan, truffle paste and pasta water until silky.",
    "Toss the mafaldine with mushrooms and sauce over low heat.",
    "Finish with black pepper and extra truffle if desired."
  ]
},

{
  id: "protein-french-toast",
  title: "French Toast",
  emoji: "🍓",
  description: "Cinnamon whole-wheat French toast with creamy yogurt, berries and peanut butter.",
  category: "breakfast",
  tags: ["high protein", "sweet", "quick"],
  servings: 1,
  time: 15,
  calories: 475,
  protein: 31,
  carbs: 59,
  fat: 13,
  fiber: 9,
  equipment: ["hob"],
  ingredients: [
    "3 slices whole-wheat bread",
    "1 egg",
    "80 g egg whites",
    "80 ml milk",
    "100 g skyr or high-protein yogurt",
    "100 g berries",
    "10 g peanut butter",
    "Cinnamon",
    "Vanilla",
    "Maple syrup or sweetener to taste"
  ],
  steps: [
    "Whisk egg, egg whites, milk, cinnamon and vanilla.",
    "Soak the whole-wheat bread in the mixture.",
    "Cook in a non-stick pan until golden on both sides.",
    "Top with yogurt, berries and peanut butter.",
    "Add maple syrup or sweetener if desired."
  ]
},

{
  id: "burger-bowl",
  title: "Loaded Burger Bowl",
  emoji: "🍔",
  description: "Crispy potatoes, protein-rich mince, avocado and melty cheese with burger sauce.",
  category: "main",
  tags: ["high protein", "bowl", "comfort food"],
  servings: 1,
  time: 30,
  calories: 520,
  protein: 35,
  carbs: 55,
  fat: 18,
  fiber: 10,
  equipment: ["airfryer", "hob"],
  ingredients: [
    "250 g potatoes",
    "120 g vegan mince",
    "30 g light cheese",
    "40 g avocado",
    "100 g lettuce",
    "50 g pickles",
    "30 g onion",
    "15 g burger sauce",
    "Paprika",
    "Garlic powder",
    "Salt and pepper"
  ],
  steps: [
    "Cut potatoes into cubes, season and airfry until crispy.",
    "Cook the mince with garlic powder, salt and pepper.",
    "Melt the cheese over the hot mince.",
    "Add lettuce, pickles, onion and avocado to a bowl.",
    "Top with crispy potatoes, cheesy mince and burger sauce."
  ]
},

{
  id: "tahini-sweet-potato-brownies",
  title: "Tahini Sweet Potato Brownies",
  emoji: "🍫",
  description: "Fudgy chocolate sweet potato brownies with nutty tahini.",
  category: "sweet",
  tags: ["meal prep", "high fibre", "chocolate"],
  servings: 4,
  time: 35,
  calories: 190,
  protein: 8,
  carbs: 23,
  fat: 8,
  fiber: 4,
  equipment: ["oven", "blender"],
  ingredients: [
    "250 g cooked sweet potato",
    "50 g tahini",
    "40 g oat flour",
    "30 g chocolate protein powder",
    "25 g cocoa powder",
    "1 egg",
    "40 ml milk",
    "20 g dark chocolate",
    "Sweetener to taste",
    "1/2 tsp baking powder",
    "Pinch of salt"
  ],
  steps: [
    "Preheat oven to 180°C.",
    "Blend sweet potato, tahini, egg and milk until smooth.",
    "Mix in oat flour, protein powder, cocoa, baking powder and sweetener.",
    "Fold through chopped dark chocolate.",
    "Bake for 20–25 minutes.",
    "Cool completely before cutting into 4 pieces."
  ]
},

{
  id: "smoothie-bowl",
  title: "Mango Berry Smoothie Bowl",
  emoji: "🥭",
  description: "Thick mango and berry smoothie bowl with oats, chia and peanut butter.",
  category: "breakfast",
  tags: ["high protein", "sweet", "quick", "high fibre"],
  servings: 1,
  time: 10,
  calories: 485,
  protein: 32,
  carbs: 66,
  fat: 12,
  fiber: 11,
  equipment: ["blender"],
  ingredients: [
    "150 g frozen mango",
    "100 g frozen berries",
    "150 g skyr or soy yogurt",
    "25 g protein powder",
    "30 g oats",
    "10 g chia seeds",
    "10 g peanut butter",
    "50–100 ml milk or water"
  ],
  steps: [
    "Blend mango, berries, yogurt and protein powder.",
    "Add only enough liquid to allow it to blend while keeping it thick.",
    "Transfer to a bowl.",
    "Top with oats, chia and peanut butter."
  ]
},

{
  id: "high-protein-tacos",
  title: "High Protein Tacos",
  emoji: "🌮",
  description: "Loaded protein-wrap tacos with seasoned mince, avocado, corn and creamy lime sauce.",
  category: "main",
  tags: ["high protein", "quick", "mexican-inspired"],
  servings: 1,
  time: 20,
  calories: 520,
  protein: 40,
  carbs: 53,
  fat: 17,
  fiber: 10,
  equipment: ["hob"],
  ingredients: [
    "2 high-protein wraps",
    "120 g vegan mince",
    "40 g avocado",
    "30 g light cheese",
    "50 g high-protein yogurt",
    "50 g corn",
    "Lettuce",
    "Lime juice",
    "Smoked paprika",
    "Cumin",
    "Garlic powder"
  ],
  steps: [
    "Cook mince with paprika, cumin and garlic powder.",
    "Warm the wraps in a dry pan.",
    "Mix yogurt with lime juice and salt.",
    "Fill wraps with lettuce, mince, corn, avocado and cheese.",
    "Drizzle with the lime yogurt sauce."
  ]
},

{
  id: "tortilla-de-patatas",
  title: "Tortilla de Patatas",
  emoji: "🥔",
  description: "Classic Spanish tortilla with soft potatoes, onion and plenty of egg.",
  category: "main",
  tags: ["Spanish", "high protein", "vegetarian"],
  servings: 1,
  time: 30,
  calories: 495,
  protein: 29,
  carbs: 45,
  fat: 22,
  fiber: 5,
  equipment: ["hob", "microwave"],
  ingredients: [
    "220 g potatoes",
    "2 eggs",
    "120 g egg whites",
    "80 g onion",
    "10 g olive oil",
    "Salt"
  ],
  steps: [
    "Thinly slice the potatoes and onion.",
    "Microwave the potatoes until almost tender.",
    "Cook onion and potatoes gently in olive oil until soft and lightly golden.",
    "Whisk eggs and egg whites with salt.",
    "Combine with the potato mixture.",
    "Cook over medium-low heat until almost set.",
    "Flip carefully and cook the other side until golden."
  ]
}
];
